### ISSUE TITLE
Linker script support

### ISSUE THREAD

**Issue by bousqi** [vpetrigo/arm-cmake-toolchains#1]
Thanks for your cmake files, they have been useful.
It would be great to add support for linker script (aka scatter files).

Do you think you could add such feature ?

**Comment by vpetrigo** [comment]
Hello @bousqi,
Thank you for you feedback. Would you tell what you mean by adding support of linker script? Would you like me to add some function/macro/whatever that allows to easily add a custom linker script file?

**Comment by bousqi** [comment]
Linker scripts are files used to define memory layout on micro controllers.
You can specify where is placed vecotrs, code, RAM, bss, and so on.

Here is a description : (random website  I found on google)
http://developers.stf12.net/cpp-demo/gcc-linker-script-and-stm32-a-tutorial

The linker script file is passed to the linker as a parameter with "-T linker_file.ld" option.
I'm new to cmake build system, but from what I found on google, the linker script must be defined in the CMakeList.txt after the include to the toolchain cmake file, and next rely on a function to modify linker options at the end.

**Comment by vpetrigo** [comment]
@bousqi I know what a linker script is. :smiley:
I just wanted to clarify:
 - you want me to add here in a repo a linker script template? I do not think it is a good idea as such files mostly project/processor specific
 - you want me to add support for adding linker script inside CMake build system?

**Comment by vpetrigo** [comment]
@bousqi would you tell if such a possible function looks reasonable for you to use?

```cmake
# ... part of a CMakeLists.txt
linker_script_add("<path/to/linker/script>/cpu.ld")
# ... part of a CMakeLists.txt
```

`linker_script_add` function are going to provide necessary flag for the linker.

**Comment by bousqi** [comment]
Exactly what I was looking for.
I curious to see how you did it. I'm pretty sure what I did is not the most elegant solution

**Comment by vpetrigo** [comment]
Hey @bousqi,

Would you review changes that have been done in #2 pull request and approve whether they match your expectations?

**Comment by vpetrigo** [comment]
Hello @bousqi,
Any luck that you were able to look through changes? :smile:
