### ISSUE TITLE
Failed to build executable target

### ISSUE THREAD

**Issue by zchrissirhcz** [vpetrigo/arm-cmake-toolchains#20]
## Environment
CMake version: 3.18.0
System: ubuntu16.04
arm-none-eabi-gcc version:
```
(base) machine% arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.9.3 20150529 (release) [ARM/embedded-4_9-branch revision 227977 with DYNAMIC_REENT by Ambarella]
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

## Problem
Thinks this scenario:  CMakeLists.txt contains a static library target  ("A"), plus an executable target ("B), and B relies A.

The linking output gives error complains like this:
```
gcc-arm-none-eabi-4_9-2015q3-amba-20160323/bin/../lib/gcc/arm-none-eabi/4.9.3/../../../../arm-none-eabi/lib/armv7-ar/thumb/fpu/libc.a(lib_a-exit.o): In function `exit':
exit.c:(.text.exit+0x1c): undefined reference to `_exit'
```

In `arm-gcc-toolchain.cmake`, L20~L24:
```cmake
if (${CMAKE_VERSION} VERSION_EQUAL "3.6.0" OR ${CMAKE_VERSION} VERSION_GREATER "3.6")
    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
else()
    set(CMAKE_EXE_LINKER_FLAGS_INIT "--specs=nosys.specs")
endif()
```

If changed them to the following:
```cmake
set(CMAKE_EXE_LINKER_FLAGS_INIT "--specs=nosys.specs")
```

Then the linking error disappears.

**Comment by vpetrigo** [comment]
Hello @zchrissirhcz,

Thank you for the report. `arm-gcc-toolchain.cmake` is intended to bootstrap your toolchain, not to set up all sort of flags for further building of an executable target. Do you have a chance to take a look at the [`led`](https://github.com/vpetrigo/arm-cmake-toolchains/blob/fcce908259b762432663a245ef533b19dd431242/examples/efm32/led/CMakeLists.txt#L37) example? Here in the main project `CMakeLists.txt` proper `specs` file explicitly specified.

Hope that answers your question.

**Comment by zchrissirhcz** [comment]
@vpetrigo Thanks for pointing out this exampls' `CMAKE_EXE_LINKER_FLAGS` configuration. I should have read it before.
