### ISSUE TITLE
No Makefile

### ISSUE THREAD

**Issue by freetoair** [vpetrigo/arm-cmake-toolchains#26]
I'm new to this, so far I've only used IDE. That's why I'm probably asking a stupid question: I did everything according to the instructions, but I only get a bunch of files for Visual Studio as an output. No Makefile. Probably the problem is in the settings that I don't know? Can you help with that?

freetoair, Thanks !

**Comment by vpetrigo** [comment]
Hello @freetoair,

Have you taken a look at the example with Ninja generator [here](https://github.com/vpetrigo/arm-cmake-toolchains#cmake-toolchain-files-for-arm-gcc-compiler)? By default if you do not specify a generator argument, CMake tool will use system default generator (Visual Studio - Windows, Unix Makefiles - Linux).
So on Windows you should specify `-G "Unix Makefiles"` (not sure that I have ever tried `MinGW Makefiles`, but that may work as well if you use `mingw32-make`) to have Makefiles generated for you.

**Comment by freetoair** [comment]
Ok, thanks for the help. That's it, now with -G "MinGW Makefiles" I get a correct Makefile file on the output.

regards, freetoair.
