### ISSUE TITLE
General clang toolchain advice

### ISSUE THREAD

**Issue by NilsHasenbanck4758** [vpetrigo/arm-cmake-toolchains#4]
Hi,

I'm currently using your toolchain scripts for building my project with ninja and using arm-none-eabi-gcc.

I would like to use clang as well to have another target to test my code, but it seems that I can't get clang to work with my project. I tried to use clang under MacOSX and Ubuntu 18.04 using your clang toolchain script, but got various errors.

Could someone probably give an example how you used clang to compile your projects using the toolchain script? (Which environment you used, how clang was set up, etc.)

**Comment by vpetrigo** [comment]
Hello @NilsHasenbanck4758.

Would you post errors you got by using `clang` CMake script? Also specifying used `clang` version as well `arm-non-eabi-gcc` would be helpful.

**Comment by hasenbanck** [comment]
@vpetrigo Currently I'm using clang 6.0.0-1ubuntu2 (ubuntu 18.04). The biggest problem I currently have, is the linking stage. Clang wants to keep using ld.lld, even though it's not installed:

```
[153/153] Linking C executable exa_tim.elf
FAILED: exa_tim.elf
: && /usr/bin/clang --target=arm-none-eabi -mcpu=cortex-m0plus -mthumb -fdata-sections -ffunction-sections -Wall -Og -g -gdwarf-2  -specs=nano.specs -specs=nosys.specs -lc -lm -lnosys -T/home/nils/Development/exa_tim/firmware/stm32_flash.ld -Wl,--gc-sections [...]

clang: warning: argument unused during compilation: '-specs=nano.specs' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-specs=nosys.specs' [-Wunused-command-line-argument]
clang: error: unable to execute command: Executable "ld.lld" doesn't exist!
clang: error: ld.lld command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

I think I had the exact same problems under Mac OSX with the clang from xcode. It seems that the toolchain doesn't use the arm-none-eabi-ld. Cmake seems to find the arm toolchain non the less (gcc-arm-none-eabi-7-2018-q2-update):

```
-- The C compiler identification is Clang 6.0.0
-- The ASM compiler identification is GNU
-- Found assembler: /opt/gcc-arm-none-eabi-7-2018-q2-update/bin/arm-none-eabi-gcc
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nils/Development/exa_tim/firmware/build
```

**Comment by vpetrigo** [comment]
Hello @NilsHasenbanck4758,

Sorry for delay. I've analyzed the issue with modern Clang versions and it seems that there is an additional dependency - `compiler-rt.builtins_arm.a` library. So it seems that it is not possible to use bundled version of Clang without compiled Compiler-rt for ARM targets (https://llvm.org/docs/HowToCrossCompileBuiltinsOnArm.html). I've tested that CMake lists while the Clang 3.5-3.9 were out there.

**Comment by hasenbanck** [comment]
Oh okay. I feared as much. I will try to compile the suit myself when I'm working at the project again. Thanks for the insight.

**Comment by vpetrigo** [comment]
@hasenbanck it passed a while since the last reply here, but anyway I'd like to notify you that I managed to introduce a workaround, so will push that changes into the repository.

**Comment by vpetrigo** [comment]
Hey @hasenbanck,

I updated toolchain files and provided an example on how to use it. So, if it is still relevant for you, give it a try. 😄

**Comment by vpetrigo** [comment]
@NilsHasenbanck4758 @hasenbanck I've also added OSX builds support within task #8 to Travis CI, so you may take a look to get a picture of using Clang for building ARM projects on OSX. If you still have a questions, just let me know.

**Comment by hasenbanck** [comment]
@vpetrigo Hi! I will try out you changes once I get working on that project again. Thx!

**Comment by vpetrigo** [comment]
Just let me know if you have any issues.
